"""YAML export service using ruamel.yaml."""

import io
import logging
from datetime import datetime, timezone

from ruamel.yaml import YAML

from app.models.screenplay import Screenplay

logger = logging.getLogger(__name__)


def export_to_yaml(screenplay: Screenplay) -> str:
    """Export a Screenplay model to a formatted YAML string.

    Uses ruamel.yaml for:
    - Preserved insertion order
    - Block-style output (no flow-style {})
    - Unicode support
    - YAML comments

    Args:
        screenplay: The complete screenplay model.

    Returns:
        YAML string representation.
    """
    # Convert Pydantic model to dict
    data = screenplay.model_dump(mode="json", exclude_none=True)

    # Wrap in top-level key
    yaml_data = {"screenplay": data}

    # Configure ruamel.yaml
    yaml = YAML()
    yaml.default_flow_style = False
    yaml.width = 120
    yaml.allow_unicode = True
    yaml.indent(mapping=2, sequence=4, offset=2)

    # Render to string
    stream = io.StringIO()

    # Add header comment
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    stream.write("# Screenplay YAML v1.0.0\n")
    stream.write(f"# Generated by novel-to-screenplay tool on {timestamp}\n")
    stream.write("# Schema documentation: docs/YAML_SCHEMA.md\n")
    stream.write("---\n")

    yaml.dump(yaml_data, stream)

    result = stream.getvalue()
    logger.info("Exported screenplay YAML (%d characters)", len(result))
    return result
