"""Tests for the YAML exporter service."""

import pytest

from ruamel.yaml import YAML

from app.services.yaml_exporter import export_to_yaml


class TestYamlExport:
    def test_export_produces_valid_yaml(self, sample_screenplay):
        yaml_str = export_to_yaml(sample_screenplay)
        assert yaml_str is not None
        assert len(yaml_str) > 0

        # Verify it can be parsed back
        yaml = YAML()
        data = yaml.load(yaml_str)
        assert "screenplay" in data

    def test_export_contains_metadata(self, sample_screenplay):
        yaml_str = export_to_yaml(sample_screenplay)
        assert "title: '1984'" in yaml_str or "title: \"1984\"" in yaml_str or "1984" in yaml_str
        assert "George Orwell" in yaml_str

    def test_export_contains_characters(self, sample_screenplay):
        yaml_str = export_to_yaml(sample_screenplay)
        assert "winston-smith" in yaml_str
        assert "Winston Smith" in yaml_str

    def test_export_contains_scenes(self, sample_screenplay):
        yaml_str = export_to_yaml(sample_screenplay)
        assert "act-1-scene-1" in yaml_str
        assert "VICTORY MANSIONS" in yaml_str

    def test_export_has_header_comment(self, sample_screenplay):
        yaml_str = export_to_yaml(sample_screenplay)
        assert "Screenplay YAML" in yaml_str
        assert "Generated by" in yaml_str

    def test_export_unicode_preserved(self, sample_screenplay):
        sample_screenplay.metadata.title = "小说改编剧本"
        yaml_str = export_to_yaml(sample_screenplay)
        assert "小说改编剧本" in yaml_str

    def test_roundtrip(self, sample_screenplay):
        """Verify YAML -> parse -> data matches original."""
        yaml_str = export_to_yaml(sample_screenplay)
        yaml = YAML()
        data = yaml.load(yaml_str)

        sp = data["screenplay"]
        assert sp["metadata"]["title"] == "1984"
        assert sp["metadata"]["author"] == "George Orwell"
        assert len(sp["characters"]) == 2
        assert len(sp["structure"]["acts"]) == 1
        assert len(sp["structure"]["acts"][0]["scenes"]) == 1
